### ISSUE TITLE
Add paymentmode fail with 500 Internal Server Error

### ISSUE THREAD

**Issue by UteHaus** [julien-nc/cospend-nc#132]
Add a new paymentmode on a project failed.

Request: `https://nextcloud.de/index.php/apps/cospend/projects/project1/paymentmode`
Body: `{"name":"Kredit 50000","icon":"🏦","color":"#8855a8","order":4}`
Status: ` 500 Internal Server Error`

**Nextcloud version:** 23.0.3
**cospend version**:  1.4.6
DB:  Postgres 11 

**Log**
[cospend-log.txt](https://github.com/eneiluj/cospend-nc/files/8524635/cospend-log.txt)

**Comment by eneiluj** [comment]
I need more information. Which Cospend version are you using? On which NC version? The browser log would be helpful. The network error in the browser dev tools network tab.
On the server side, some error most likely pops up in nextcloud.log.

I can't reproduce this issue with Cospend v1.4.6 on NC 23.

**Comment by UteHaus** [comment]
In my first post, I write the NC and cospend version. A server log is now also included, see link.
 It looks like a second/same payment mode entry with a fixed/existing ID is created in the database.

**Comment by eneiluj** [comment]
Could you run this SQL query?

```
SELECT * FROM oc_cospend_paymentmodes WHERE projectid="hoha";
```

This issue has only been reported when using PostgreSQL. Really no idea what happens for now.

**Comment by UteHaus** [comment]
With double quotes `"` the query runs incorrectly (column hoha not present). If I use `'hoha'` instead of single quotes, the query runs without errors.

(Some information for postgres and quotes using: https://www.prisma.io/dataguide/postgresql/short-guides/quoting-rules)

**Comment by UteHaus** [comment]
The Bug exist but with a new exception
Nextcloud Version 25.0.1
App Version: 1.5.2
```
OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »oc_cospend_categories_pkey« DETAIL: Schlüssel »(id)=(24)« existiert bereits.
/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php - line 329:

OC\DB\Exceptions\DbalException::wrap(Doctrine\DBA ... {})

/var/www/html/custom_apps/cospend/lib/Service/ProjectService.php - line 4091:

OC\DB\QueryBuilder\QueryBuilder->executeStatement()

/var/www/html/custom_apps/cospend/lib/Controller/PageController.php - line 2480:

OCA\Cospend\Service\ProjectService->addCategory("test", "test-new", "😭", "#a5b872", 11)

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 225:

OCA\Cospend\Controller\PageController->addCategory("test", "test-new", "😭", "#a5b872", 11)

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 133:

OC\AppFramework\Http\Dispatcher->executeController(OCA\Cospend\ ... {}, "addCategory")

/var/www/html/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\Cospend\ ... {}, "addCategory")

/var/www/html/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main("OCA\\Cospen ... r", "addCategory", OC\AppFramew ... {}, [ "test","co ... "])

/var/www/html/lib/base.php - line 1047:

OC\Route\Router->match("/apps/cospe ... y")

/var/www/html/index.php - line 36:

OC::handleRequest()

```

**Comment by UteHaus** [comment]
It looks like it was a Nextcloud core issue. The creation of payment types works with Nextcloud 30 and cospand 3.0.8.
