### ISSUE TITLE
imported a CSV project, can't open Cospend anymore at all

### ISSUE THREAD

**Issue by mortee** [julien-nc/cospend-nc#174]
I just created a CSV file by exporting a project as a template, and while keeping the structurre, I populated it with my bill records. After importing it, I can no longer access any project: when I openn the Cospend page, it gives me an error, and the projects sidebar remains empty. I get this in the NC log:
```
{"reqId":"UtjJL27U9EGRfA1ndBAn","level":3,"time":"2022-09-09T12:59:28+00:00","remoteAddr":"xx.xx.xx.xx","user":"xx","app":"index","method":"GET","url":"/apps/cospend/projects","message":"Could not json_encode due to invalid non UTF-8 characters in the array: array (\n  0 => \n  array (\n    'userid' => '...
```

**Comment by mortee** [comment]
Wow, is this issue _so_ inconsequential that literally nobody even notices?... 🙄

**Comment by eneiluj** [comment]
Well I don't have much time these days. If you want to increase chances I check what happens you can provide the csv file (with only a subset of the bills if you don't want me to know too much :grin:)

First guess: You operating system wrote non-utf8 characters in the file.

**Comment by mortee** [comment]
I lilterally exported an existing project, and only changed the bill records. Sure, there are a few accented chars in there, but the whole thing is supposed to be proper UTF-8.
[cospend-import-example.csv](https://github.com/eneiluj/cospend-nc/files/9601021/cospend-import-example.csv)

**Comment by julien-nc** [comment]
Thanks for providing an example file. The category and payment modes are indeed non-utf8 characters for some reason. Maybe your text editor wrote them differently than they were written initially by Cospend (Php in fact).

Anyway the import process is now checking if those icon characters are valid and avoids them if not. This will be available in the next release (Nextcloud 25 only, sorry).

In the meantime, in the database, you can set the "icon" to NULL for all the imported categories and payment modes in the database and Cospend will work again.

**Comment by mortee** [comment]
Yeah, thanks! This is what I've been hoping for: check on import, and don't put something into the DB if that won't be able to be read later.

I'll try your NULL solution.

And no worries, I'll upgrade to 25 a soon as the docker image becomes available.
