### ISSUE TITLE
Nextcloud 25.0 compatibility

### ISSUE THREAD

**Issue by rriemann** [julien-nc/cospend-nc#180]
Dear all,

thanks for cospend – I use it regularly. Unfortunately, the GUI is partially broken since the Nextcloud 25 (Hub 3) update. The scrolling of the bill creation page is not working, so that some controls remain inaccessible.

**Comment by rriemann** [comment]
I think this problem is limited to mobile view (narrow screen). Here, I recorded the problem with an empty project using Firefox on my Linux computer. There is no scrollbar. I can only reach the fields outside of the initial screen using the tab key (which I don't have on mobile).

https://user-images.githubusercontent.com/111932/199518913-849e46e0-3706-400a-b067-ca05565c7fa0.mp4

**Comment by eliandoran** [comment]
@julien-nc , I was able to reproduce the issue using Firefox on desktop. Created this PR which solves the issue for me: #184

**Comment by siccovansas** [comment]
@julien-nc there hasn't been a new release yet which includes this fix and it seems that the nightly isn't up to date. How can I incorporate this fix myself until there is a new release? I tried adding the fixed code to `html/custom_apps/cospend/css/cospend.scss`, but that doesn't seem to change the CSS when I load the website (even after a Nextcloud restart).

**Comment by julien-nc** [comment]
@siccovansas The scss file is imported by a frontend script when it is compiled so you would need to build the app from the sources.

Easier path: v1.5.4 is out :grin:.

**Comment by siccovansas** [comment]
Thanks for the answer. And even better, thanks for the release :D!
