### ISSUE TITLE
[BUG] Wrong display of "who paid?" and "for whom?"

### ISSUE THREAD

**Issue by linux-lukas** [julien-nc/cospend-nc#182]
### A. Problem / Goal

In the current version of Cospend 1.5.2 (and probably in those before) there is a display error. 

Example: Person 1 pays person 2 an invoice. 

- Who has paid? => person 1
- For whom? => Person 

As can be seen in the screenshot, however, this process is displayed exactly the other way round. 

In fact, person 1 should be debited according to the contribution, and person 2 should be credited.

![20221105_cospend_fail_001](https://user-images.githubusercontent.com/47597136/200144278-76947c8d-002c-4dbf-9a2d-4004b88ab8bc.png)

![20221105_cospend_fail_002](https://user-images.githubusercontent.com/47597136/200144276-f3f84c80-1be6-4a12-b130-120b0268e7c2.png)

### B. Solution

The considered solution would be to look where there might be a bug in the code and fix it with a new release.

### C Alternatives

None.

**Comment by Porrumentzio** [comment]
What was the conclusion with this issue? I'm facing the same problem, it seems
