### ISSUE TITLE
Cannot add password to sharing link

### ISSUE THREAD

**Issue by josealberto4444** [julien-nc/cospend-nc#194]
Hi, I'm trying to add a password to a sharing link and it says "share link saved", but it remains as if I hadn't done it.

It happens the same when trying to add a label to the link. It says "share link saved" but doesn't do anything.

I'm not using the deprecated password protected access, but the new share links. I'm using Nextcloud 25.0.3 and I'm glad to provide more information if needed.

**Comment by julien-nc** [comment]
Thanks a lot for the bug report. Can you try [v1.5.7-1-nightly](https://github.com/julien-nc/cospend-nc/releases/download/v1.5.7-1-nightly/cospend-1.5.7-1-nightly.tar.gz) which should fix this? I'll publish a release right after we confirm it's fixed.

**Comment by julien-nc** [comment]
And btw, this was caused by a change in a Vue component that is used for the label and the password which broke the way Cospend gets the value on submission.
As there are still no frontend tests, these kind of issues can slip under my radar... So big thanks again for reporting this.

**Comment by josealberto4444** [comment]
I only have access to the admin panel in Nextcloud web, but I don't have proper admin access to the machine running it. Is there any way to install it from there? Sorry for the inconvenience. =(

**Comment by julien-nc** [comment]
No worries, I'm pretty confident in the fix. v1.5.7 is on its way. You should be able to upgrade in less than an hour.

**Comment by josealberto4444** [comment]
Thank you very much! ^^

**Comment by josealberto4444** [comment]
I can confirm it's fixed in v1.5.7! 🎉

**Comment by julien-nc** [comment]
That was a quick one! Thanks for you feedback.

As you are probably the first to have used v1.5.7, have you noticed a difference in the Cospend page load time? The main script size went from 6.4 MB to 1 MB thanks to Webpack lazy loading.

**Comment by josealberto4444** [comment]
Oops, I have no idea, I had just started using it today some minutes before I opened this issue, so I didn't get used to any loafing times, sorry.
