### ISSUE TITLE
Cospend does not work on Android anymore 

### ISSUE THREAD

**Issue by Tommot8** [julien-nc/cospend-nc#197]
Since a few days, cospend is oddly displayed on mobile browsers and you cannot enter any data. See screenshot.
May I ask for a fix, please?
![Screenshot_20230215-181825_Brave](https://user-images.githubusercontent.com/125491942/219104958-1a77c080-b23d-4b2e-a176-b82871d9596f.jpg)

**Comment by Neraste** [comment]
I have the same issue with Nextcloud 25.0.1 and Cospend 1.5.7.

I can obtain the same problem on Firefox mobile, and on desktop with Firefox using development tools, Responsive Design Mode, and refreshing the page. On log console, I get the following backtrace:

```log
TypeError: e is undefined ([vue.runtime.esm.js:3049:16](webpack:///cospend/node_modules/vue/dist/vue.runtime.esm.js))
    VueJS 22
    checkListSlot NcAppContent.js:2
    updated NcAppContent.js:2
    VueJS 12
    addProject App.vue:842
    getProjects App.vue:745
    promise callback*getProjects App.vue:735
    created App.vue:324
    VueJS 4
    ce main.js:109
    <anonymous> main.js:89
    EventListener.handleEvent* main.js:79
    <anonymous> main.js:104
    <anonymous> main.js:104
vue.runtime.esm.js:3049:16
```

**Comment by julien-nc** [comment]
Thanks for reporting this.
There is a weird bug in Vue. I don't exactly understand if it's caused by `@nextcloud/vue` or by Vue itself but I found a way to avoid the bug.
This should be fixed by v1.5.8. Could you confirm?

**Comment by Tommot8** [comment]
Working again after updating the app. Thank you very much for the quick fix!

**Comment by julien-nc** [comment]
@Tommot8 Nice! Thanks for the lightning fast feedback.
