### ISSUE TITLE
Question regarding recurring bills

### ISSUE THREAD

**Issue by nicofrand** [julien-nc/cospend-nc#215]
Hi,

first I'd like to thank you for this wonderful app.

There is a thing that I do not get and could not find in the user documentation:

I have a recurring bill of, let's say, 100€. Then from now on it will be 110€. How do I edit only the next (recurring) bills and not the past bills?

**Comment by julien-nc** [comment]
Hey, thanks for your enthusiasm.

When a bill is repeated, Cospend creates a new bill, enables repetition for this new bill, and removes repetition for the first bill.
So if you just edit the last bill (the one with the repetition flag), only this bill and the future ones will be affected. It does not go backward, there is no link between a repeated bill and its past occurrences.

Cheers
