### ISSUE TITLE
Unable to import csv-file from splitwise in NC 27

### ISSUE THREAD

**Issue by Matsched** [julien-nc/cospend-nc#216]
NC Version: 27.0
Cospend Version 1.5.10

If i try to import a exported .csv-File from SplitWise i get:
`Fehler beim Importieren der Projektdatei: Malformed CSV, impossible to find the column names`
(Error while importing the project data)

This is the format from splitwise:
```
Datum,Beschreibung,Kategorie,Kosten,Währung,Name1,Name2
2023-06-22,Lebensmitteleinkauf REWE,Lebensmittel,2,EUR,-1,1
```
How i can change it to import it correctly to Cospend?
Can you fix this?

kind regards

**Comment by k-jell** [comment]
Maybe have a look here: 
https://gitlab.com/eneiluj/cospend-nc/-/merge_requests/152

> It only works if Splitwise account language is set to English (column names are localized)

Not sure if this is still the case, but it seems like it was, when the feature was implemented.

**Comment by Jolg42** [comment]
The code is here after a quick search
https://github.com/julien-nc/cospend-nc/blob/ebfd417293f9eaa2a248354c5264c599ae41aa7a/lib/Service/ProjectService.php#L5178

Especially these lines
https://github.com/julien-nc/cospend-nc/blob/ebfd417293f9eaa2a248354c5264c599ae41aa7a/lib/Service/ProjectService.php#L5201-L5205
