### ISSUE TITLE
Cannot select csv (Splitwise format) file for import NC 27.1

### ISSUE THREAD

**Issue by k-jell** [julien-nc/cospend-nc#225]
Nextcloud Version: 27.1.0
Cospend Version: 1.5.10

I am trying to import a csv, that I exported from splitewise. But in the popup window where I can select a file nothing happens, when I click on the csv-file. In some other issue I found a dummy csv file which I also tried, but same result:

```
Date,Description,Category,Cost,Currency,Person A,Person B

2016-07-02,Food,General,45.00,EUR,-22.50,22.50
2016-07-03,Breakfast,General,25.00,EUR,12.50,-12.50
2016-07-04,Something,General,18.00,EUR,9.00,-9.00
```
I clicked everywhere possible I think, but nothing happens, no error message and nothing in the logs.

![image](https://github.com/julien-nc/cospend-nc/assets/42188452/772cc20e-07ff-48a9-ab6d-dd826855e505)

I know there are a bunch of issues regarding imports, but most if not all of them are about error messages with malformed csv files or something like that. But I don't get any messages like that.
Maybe I am being very stupid and overlooking something. Would appreciate any hint on how to do it. Or could it be a compatibilty issue with Cospend and NC 27.1.0?

**Comment by Deathproof76** [comment]
same here🤷‍♂️

**Comment by Deathproof76** [comment]
@k-jell I'm on the docker aio beta channel and just installed the update for NC 27.1.2. Tested again and importing of csv via ui works again!

**Comment by k-jell** [comment]
@Deathproof76 thanks! Can confirm, importing works again after updating to NC 27.1.2.
