### ISSUE TITLE
Bug: Overlapping menu and back button on start page in mobile/small mode

### ISSUE THREAD

**Issue by brunothg** [julien-nc/cospend-nc#230]
When opening the cospend app in small mode (collapsed menu) the menu button sometimes overlaps the back button of the start page (what do you want to do screen), so that there's no way to get to the list of bills.
This seems to be a kind of race condition. Switching between files app and cospend app will often fix it temporarily. But the problem occours near 100% of the time when opening copsend for the first time after some time (or disabled cache on desktop chrome browser when in mobile simulation mode).

Would be nice if this can get fixed.
For me it would even be better if this welcome screen can become configurable and so can be turned off (at least for mobile/small screens).

![Screenshot 2023-10-01 105127](https://github.com/julien-nc/cospend-nc/assets/6464629/f297057a-0e59-482c-8b10-0fc590362853)

Nextcloud version: 27.1.1 (26.x.x  also affected - others don't know)
Cospend version: 1.5.10
DB Type: Maria DB
Browser: Chrome, Edge, Firefox (Desktop & Android)

**Comment by julien-nc** [comment]
I can't reproduce anymore, I think it was fixed in the Nextcloud Vue library.
v1.5.11 is coming very soon. It would be nice to have your confirmation it's fixed then.

**Comment by brunothg** [comment]
You're right. Seems to be fixed with latest version (1.5.12)
