### ISSUE TITLE
Import csv file dialog does not work

### ISSUE THREAD

**Issue by benhiemer** [julien-nc/cospend-nc#232]
Not so sure if I found a bug or just have a question.

I am trying to import a .csv project and cannot find out how to do the last step.

I click "New project" -> "Import csv project" and a file picker dialog opens (title: "Choose csv project file"). 
Then I navigate to my .csv file, select it and then...nothing happens. What is supposed to happen now? I do not see a OK button, but just selecting the file does not seems to be enough to trigger the import. 

I have two ideas:

1) selecting the file should be enough but the import fails. But I neither see any error messages nor do I have any idea why the file should not work. I simplify the file to this, still it does not work:

```
name,weight,active,color
"Person",1,1,"#0082c9"
"Karl",1,1,"#6ea68f"

what,amount,date,timestamp,payer_name,payer_weight,payer_active,owers,repeat,repeatfreq,repeatallactive,repeatuntil,categoryid,paymentmode,paymentmodeid,comment
"Supermarket",72,2022-01-01,1641074411,"Person",1,1,"Person,Karl",n,1,0,,57,n,0,""

categoryname,categoryid,icon,color
"Grovery",57,"🛒","#ff9595"

paymentmodename,paymentmodeid,icon,color
"Cash",12,"💵","#556B2F"
```

2) it is an UI issue and I should see something like a OK button to confirm/start the import. My dialog looks like this:
![Conspend](https://github.com/julien-nc/cospend-nc/assets/16649926/b4187e72-b66b-4c68-ae39-7350bc4ce8e0)

So my question is: How is the import dialog supposed to work, am I doing something wrong or could this be a bug?

Information
My Nextcloud Version: 27.1.2
Cospend Version:  1.5.10

I tried with various browsers:
Chromium (Version 117.0.5938.149 (Official Build) (64-bit))
Firefox (Version 118.0.2 (64-bit))
Chrome (Version 118.0.5993.70 (Official Build) (64-bit))

Last but not least: Thank you very much for Cospend, it is a great tool :-)

**Comment by alct** [comment]
Hello, see #228

**Comment by benhiemer** [comment]
My bad, you are right. I missed the other issue because it is closed.

And I thought I was running the newest Nextcloud version (27.1.2), but it was 27.1.1.
I updated to 27.1.2 and now it works again. Thank you!
