### ISSUE TITLE
Bullet symbol in bill list

### ISSUE THREAD

**Issue by brunothg** [julien-nc/cospend-nc#254]
I don't know, if this should be a feature or a bug.
But if it is a feature, it might be a candidate for a change in the future!?
Every entry in the bill list displays the browsers default bullet icon for &lt;li&gt; elements.
Maybe a style like the following will fix it?:

      .billItem {
         list-style-type: none;
       }

![Screenshot 2024-01-26 161903](https://github.com/julien-nc/cospend-nc/assets/6464629/678999c3-1d90-4135-99a2-f50ad19cdc98)

Version: at least 1.5.12 - 1.5.14

**Comment by julien-nc** [comment]
This is already fixed in the development version. It will be included in the next release.

**Comment by brunothg** [comment]
> This is already fixed in the development version. It will be included in the next release.

You're fast 🏃💨
Thanks

**Comment by brunothg** [comment]
Seems to be fixed with 1.6.1
