### ISSUE TITLE
No keyboard when creating a bill on iOS from browsers

### ISSUE THREAD

**Issue by Kr0kspluish** [julien-nc/cospend-nc#255]
Hello, 

I can't use Cospend on iOS from the browser anymore as the keyboard doesn't show up when clicking fields in bill creation. It used to work but I can't say precisely when it stopped working, about a month ago or so. I tried with Safari and Duckduckgo.

I use Nextcloud 28.0.1 (docker version) and Cospend 1.5.14, and the phone runs iOS 17.3. It didn't work with iOS 17.2.x either.

I can try to install Cospend from git to bisect but not sure how I would do so with the docker version.

**Comment by opi1994** [comment]
I have the same problem with Android and Chrome Browser 121.
Also using Nextcloud docker Server version 28.
With NC27 keyboard opened up.

**Comment by Kr0kspluish** [comment]
I did not notice the problem on Android as I use the MoneyBuster client for Cospend, but now that you say it, I checked as well. And indeed, on my Android phone, no keyboard either, on DuckDuckGo and Firefox alike.

The only usable fields are the date/time selector and the tickbox to select participants.

**Comment by Kr0kspluish** [comment]
And I just realised that this is a duplicate of #248. 

Sorry for the noise, I close this one.
The workaround in the above issue worked for me, thanks.
