### ISSUE TITLE
Unable to calculate in (personal) amount fields anymore

### ISSUE THREAD

**Issue by ndi123** [julien-nc/cospend-nc#257]
Using v1.6.0 it is no longer possible to make calculations in the (personal) amount fields. All calculations always result in zero.

Edit:

Strangely, I see a CSP error in the debugger when I try to calculate something

![grafik](https://github.com/julien-nc/cospend-nc/assets/34609222/3728022f-dd70-4525-98c3-18d7bb75b439)

**Comment by julien-nc** [comment]
Thanks, this is now fixed and will be included in the next release.

**Comment by julien-nc** [comment]
Fixed in v1.6.1. Reopen if needed.
