### ISSUE TITLE
Bug: When in a bill we used to be able to put a sum in the "how much" section and get a total back. Now it is not working.

### ISSUE THREAD

**Issue by hackybrittle** [julien-nc/cospend-nc#259]
When in a bill on cospend we used to be able to put a sum in the "how much" section and get a total back. This does not work now and the numbers are rejected. So say I put in 24+5 and hit enter it returns to 0. This did not used to be the case.

![20240221_120130(3)](https://github.com/julien-nc/cospend-nc/assets/76405307/863b16ee-5a6b-4b6a-b983-6e29f25b86b5)

**Comment by julien-nc** [comment]
Fixed in v1.6.1. Reopen if needed.
