### ISSUE TITLE
Repeat entry not repeating?

### ISSUE THREAD

**Issue by eikaramba** [julien-nc/cospend-nc#261]
first up, i might not understand how the repeat feature works. i really tried to understand it from the source resp. issues, but haven't found a clue.

i have a repeating expense for the apartment rent. it is scheduled to repeat every month. when i created it in january i already saw the entry beginning in february and **thought everything is fine and the system will just already show the ones in the future and then create one when the date arrives.**

but it hasnt' - i still just see the repeating entry. so my question is if no "repeat until" is set. meaning no limit, are no repeating instances created of the entry?

Clicking the "repeat now" button is showing "nothing to repeat"

![grafik](https://github.com/julien-nc/cospend-nc/assets/1320525/dcd2414b-56c2-4aac-8142-441bab4aa67e)

some debug info:

nc 28.0.1
cospend 1.6.0
cronjob active and working

**Comment by eikaramba** [comment]
i also run cospend:repeat-bills, but it did not create anything.

**Comment by eikaramba** [comment]
ok i changed the start date to 28.01 (one month earlier) and now hitting the "repeat now" button actually created an entry. the january one ;) so at least i understand the basic function now, what is confusing for me is that it seems to create the entry just when the timespan of the repeating timeframe has elapsed. and then it create the one in the past.

i will close this ticket now because i think it is not a problem and i was just confused about how it works.

A little explanation in the readme about how the repeating function works would be nice however to avoid any future users confusion. neverthless i appreciate your work!

**Comment by bertwesarg** [comment]
That hit me too, but I still don't understand how it works based on your comment. What is "the repeating timeframe has elapsed"?

I'm currently testing Cospend for me and created a test project (on 1970-01-01) with just one daily repeating bill ($100) starting tomorrow (1970-01-02). That already revealed #310 for me, i.e., the balance is already $50/-$50. On 1970-01-02 nothing has changed, there is just this one repeating bill (dated 1970-01-02) in the list but the balance is now as expected $50/-$50. Today is 1970-01-03 and nothing has changed! Still one bill (dated 1970-01-02) and balance is $50/-$50. I would say the "repeating timeframe" should have elapsed now, right?

What am I missing?

**Comment by bertwesarg** [comment]
Btw, cron job is working.

I ran `cospend:repeat-bills` manually today (1970-01-03) and the bill for 1970-01-02 was created and the balance is now $100/$-100. I will observe this for some more day to see, if the bills are created automatically.
