### ISSUE TITLE
Wrong rendering of avatars in Safari

### ISSUE THREAD

**Issue by LouisFaure** [julien-nc/cospend-nc#262]
Salut @julien-nc !

I noticed that in Safari, both coloured and image avatars are wrongly rendered:
![Screenshot 2024-03-03 at 12 05 53](https://github.com/julien-nc/cospend-nc/assets/27488782/0845559b-c101-4746-9f24-b1f0ae4acfae)

The coloured avatar is stretched two times over the height of its parent div, and the image is moved right below its parent div.

I could recover this by adding the css properties:
 -  For the coloured avatar: `position: absolute` and `width:100%` to `.initials-avatar`, I think this can be changed here: https://github.com/julien-nc/cospend-nc/blob/7188db105fc50b87b9dd7c2cba61f24a59e0c049/src/components/avatar/ColoredAvatar.vue#L103-L112
 -  For the avatar with image: `position: absolute` to `.avatardiv img`. For this one I don't know where this is showing up in the source code.

Doing these two changes lead to a better result, but there are still the bullets points showing next to each first lines, something I am not seeing on other browsers:
![Screenshot 2024-03-03 at 12 14 15](https://github.com/julien-nc/cospend-nc/assets/27488782/3db85230-0234-4a2e-af19-87c51548301a)

**Comment by julien-nc** [comment]
@LouisFaure Thanks for the issue. As you know, apple makes it difficult to use safari if you don't buy a device from them. I don't want to spend to much effort on supporting this browser.

I included your suggested changes and adjusted to make sure it does not break the style on Firefox and Chromium. Could you try those changes in safari? https://github.com/julien-nc/cospend-nc/commit/23fa9d133b3ef54559594b58b78434ce4d2fdb70

**Comment by LouisFaure** [comment]
Just tested on Safari in [development mode](https://github.com/julien-nc/cospend-nc/blob/23fa9d133b3ef54559594b58b78434ce4d2fdb70/docs/dev.md#development-environment) and now everything renders well! (Chrome and Firefox are unaffected)

**Comment by julien-nc** [comment]
Nice, thanks for checking! This will be included in the next release.
