### ISSUE TITLE
Wrong German translation of category "transport"

### ISSUE THREAD

**Issue by ruedigerkupper** [julien-nc/cospend-nc#264]
The category had always been correctly translated with „Transport". This has recently changed to "übertragung" which is just ridiculously wrong in this context. Please revert this absurd change.

**Comment by MrRinkana** [comment]
There are two translations for transport in crowdin:

One that translates to Transport
Key: category_transport
category_transport
File: [strings.xml](https://crowdin.com/editor/moneybuster/146/en-de)

One that translates to Übertragung:
Key: Transport
#: /datadisk/tera/julien/html/dev/server/apps/cospend/lib/Migration/Version000406Date20200426154317.php:102
#: /datadisk/tera/julien/html/dev/server/apps/cospend/lib/Service/ProjectService.php:126
File: [cospend.pot](https://crowdin.com/editor/moneybuster/195/en-de)

The path of the second one looks a bit weird.

I could change the translation, but maybe it's better if someone that speaks german takes the lead. [Link](https://crowdin.com/editor/moneybuster/all/en-de?view=comfortable&filter=basic&value=3#q=transport)

**Comment by call-me-matt** [comment]
Created a crowdin account and corrected this. It should be the same word for both. Set it to `Transport` (as `Übertragung` means `Transfer`).

**Comment by MrRinkana** [comment]
Awesome! Then this can be closed next time translations are pulled @ruedigerkupper !

**Comment by ruedigerkupper** [comment]
Thank you!!
