### ISSUE TITLE
In API payedFor returns an error

### ISSUE THREAD

**Issue by Pfeiffenrohr** [julien-nc/cospend-nc#265]
Since the new version I always get an error when I send a Post request to create a new bill. This worked for me until I updated to version 1.6.1.

The error is:
 {
    "ocs": {
        "meta": {
            "status": "failure",
            "statuscode": 400,
            "message": ""
        },
        "data": {
            "error": {
                "payed_for": "Ungültiger Wert"
            }
        }
    }
}
I attached my request from Postman
![postman](https://github.com/julien-nc/cospend-nc/assets/44580842/33413df9-8244-45ce-b647-ea98633da1cc)

**Comment by Pfeiffenrohr** [comment]
I have the same issue with curl:
curl --basic -u myname:**** -X POST ***/ocs/v2.php/apps/cospend/api/v1/projects/test2/bills --header 'Accept: application/json, text/plain' --header 'OCS-APIRequest: true' -d "date=2024-03-23&what=raclette&payer=58&payed_for=9&amount=200&repeat=n" 80
{"ocs":{"meta":{"status":"failure","statuscode":400,"message":""},"data":{"error":{"payed_for":"Ung\u00fcltiger Wert"}}}

**Comment by julien-nc** [comment]
Hi, you were a bit too fast to switch to the new OCS API. 
`payed_for` changed to `payedFor` in the bill creation endpoints in v1.6.1.

You can install the [ocs_api_viewer](https://apps.nextcloud.com/apps/ocs_api_viewer) app to browse the Cospend API doc.

**Comment by Pfeiffenrohr** [comment]
Oh, thanks for this fast answer. I will fix it by me
