### ISSUE TITLE
Landing page for public links on mobile view should show expenses

### ISSUE THREAD

**Issue by call-me-matt** [julien-nc/cospend-nc#280]
When sharing a cospend link with the public, the landing page shows several options, but I think it would be a much better user experience to start with the list of expenses. Especially, as the public link is normally shared with participants to verify or add new expenses and the options menu appears when scrolling down to the end of the list.

<table><tr><td>As-is:</td><td>To-be:</td></td>
<tr><td>

![Screenshot from 2024-06-09 23-19-14](https://github.com/julien-nc/cospend-nc/assets/34400929/1b4e1a27-0006-43e5-a562-aa2311d243ac)

</td><td>

![Screenshot from 2024-06-09 23-20-09](https://github.com/julien-nc/cospend-nc/assets/34400929/7a5b398b-e316-4fe6-98a1-1a9963ad2904)

</td></tr></table>

Today, the list of expenses can be reached via the small arrow on top, which is not evident to new users. If not starting with the list of expenses, there should be an additional menu option for showing the list of expenses.

**Comment by tobika** [comment]
Came here to create the same issue before seeing that this one exists already :)

**Comment by julien-nc** [comment]
Thanks for the suggestion. It's done and will be included in the next release (for Nextcloud 30).

**Comment by call-me-matt** [comment]
Awesome 🥳🥳
Thank you
