### ISSUE TITLE
Unable to use cospend

### ISSUE THREAD

**Issue by returntrip** [julien-nc/cospend-nc#306]
First time user here.

After I installed and enabled cospend on NC 30 I get this error:

[no app in context] Error: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_cospend_projects' doesn't exist
	GET /ocs/v2.php/apps/cospend/api/v1/projects
	from 10.0.1.212 by returntrip at Sep 20, 2024, 11:50:32 PM

It is like the DB entries are not created.

**Comment by julien-nc** [comment]
Hi, the tests are working fine. I double checked and tried to reproduce your issue:
* Deploy a fresh NC 30 instance
* Install Cospend from the appstore
* Create a project

It works fine.

Was there any issue/warning displayed when you installed the app?

Do you have access to your database? If so, can you run this SQL query and provide the result:
``` sql
SELECT * FROM oc_migrations WHERE app="cospend";
```
This will help to check if the database migration steps all ran successfully.

Can you also check if there is any `oc_cospend_*` table in your database?

A simple way to try to install the app again is to delete all cospend-related rows in `oc_migrations`, disable/uninstall the app and install it again.

**Comment by returntrip** [comment]
I followed your advice and deleted the cospend rows from oc_migratins  then  reinstalled the app. It seems working now. Thanks for the help!
