### ISSUE TITLE
Activate a user

### ISSUE THREAD

**Issue by shoetten** [julien-nc/cospend-nc#316]
I would like to (re) activate a user, because some users were not part of the group for a while, but will be again in the future. Unfortunately, once deactivated, i can't find any way to re add them to the project. Am i missing something or is this a missing feature?

Thank you for a very handy project!

**Comment by julien-nc** [comment]
* Either the member is related with some bills and you can disable/enable it
* Or the member is not related with any bill and it is only possible to delete it

In the first case, enabling can be done with the same action as disabling:

[Kooha-2024-12-23-22-02-57.webm](https://github.com/user-attachments/assets/7dcb0bd4-2716-4c34-9610-af152984f11e)

Or maybe I didn't get what situation you are facing. Feel free to reopen this issue if needed.
