### ISSUE TITLE
Update to 3.0.4 failed, Nextcloud unavailable

### ISSUE THREAD

**Issue by Toastyyy3** [julien-nc/cospend-nc#320]
When trying to upgrade from 3.0.3 to 3.0.4 I get an exception which makes my nextcloud instance unavailable as it’s stuck in the “App Update required” screen. Manually disabling the maintenance mode does not work. For error details see screenshot.

![IMG_5444](https://github.com/user-attachments/assets/f40ad1d1-0ad2-4230-a3bb-2b03c2b6ae48)

**Comment by lkempf** [comment]
Have a look at #321 (which is technically a duplicate). It contains instructions on how to fix the issue.

**Comment by julien-nc** [comment]
Can you try with v3.0.8? This should be fixed.

**Comment by Toastyyy3** [comment]
Yes, it's indeed fixed. Thank you so much!
