### ISSUE TITLE
Problem with database migration with Postgresql

### ISSUE THREAD

**Issue by tpokorra** [julien-nc/cospend-nc#321]
```
php occ app:update --all -n --no-ansi

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
cospend new version available: 3.0.5
Error: Database error when running migration 030000Date20240910234723 for app cospend
An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "user_id" of relation "oc_cospend_projects" contains null values
cospend couldn't be updated
```

This is with a postgresql database.

The code of the migration is here: https://github.com/julien-nc/cospend-nc/blob/main/lib/Migration/Version030000Date20240910234723.php#L14

**Comment by tpokorra** [comment]
I fixed it manually for a couple of columns:

```
alter table oc_cospend_projects add column user_id varchar(64);
update oc_cospend_projects set user_id = userid;
alter table oc_cospend_projects alter column user_id set not null;

alter table oc_cospend_bills add column project_id varchar(64);
update oc_cospend_bills set project_id = projectid;
alter table oc_cospend_bills alter column project_id set not null;

alter table oc_cospend_bills add column payer_id integer;
update oc_cospend_bills set payer_id = payerid;
alter table oc_cospend_bills alter column payer_id set not null;

alter table oc_cospend_shares add column project_id varchar(64);
update oc_cospend_shares set project_id = projectid;
alter table oc_cospend_shares alter column project_id set not null;

alter table oc_cospend_bill_owers add column bill_id integer;
update oc_cospend_bill_owers set bill_id = billid;
alter table oc_cospend_bill_owers alter column bill_id set not null;

alter table oc_cospend_bill_owers add column member_id integer;
update oc_cospend_bill_owers set member_id = memberid;
alter table oc_cospend_bill_owers alter column member_id set not null;

alter table oc_cospend_members add column project_id varchar(64);
update oc_cospend_members set project_id = projectid;
alter table oc_cospend_members alter column project_id set not null;

alter table oc_cospend_paymentmodes add column project_id varchar(64);
update oc_cospend_paymentmodes set project_id = projectid;
alter table oc_cospend_paymentmodes alter column project_id  set not null;

alter table oc_cospend_categories add column project_id varchar(64);
update oc_cospend_categories set project_id = projectid;
alter table oc_cospend_categories alter column project_id set not null;
```

after this, the upgrade went through smoothly:

```
php occ app:update --all -n --no-ansi
```

**Comment by lkempf** [comment]
Thanks for posting the steps. I also had to add

```
alter table oc_cospend_currencies add column project_id varchar(64);
update oc_cospend_currencies set project_id = projectid;
alter table oc_cospend_currencies alter column project_id set not null;
```

**Comment by MacLemon** [comment]
Additional data points:

# Workaround (Confirmed working)
Manually downgrading Cospend [to 2.0.0](https://apps.nextcloud.com/apps/cospend/releases?platform=30#30) works. (Remove the `cospend` folder in the `apps` folder and unpack the 2.0.0 release there. Re-enable Cospend. Don't forget to turn off an existing app-autoupdate `cron` job you may have.)

All my Cospend projects are there and seem to be working after the downgrade.

## Incompatibility

Neither 3.0.4, nor 3.0.5 work with Nextcloud 30.0.4.
No repeating the error message, since it's identical to the original poster's one.


## Version information
- PHP: 8.3.14
- DB: PostGreSQL 13.18

**Comment by provokateurin** [comment]
I can also confirm that downgrading works.
Luckily it's the first migration that fails right away, so no changes are made at all.
You don't need to restore a backup, just replace the code with the 2.0.0 version.

**Comment by joho500** [comment]
I have the same problem with Nextcloud AIO. The workaround mentioned above for me isn't a solution to embark on. I disabled the app and hope that the developer will create a solution for updating with a new version of the app.

**Comment by julbroa** [comment]
i have same problem. i disabled the app
![image](https://github.com/user-attachments/assets/465879d4-4d1c-4d0f-8df0-8547c656710f)

**Comment by julien-nc** [comment]
v3.0.6 contains a fix for the problematic migration. The `oc_cospend_projects.user_id` column can now contain null. I forgot that there could be existing "anonymous" projects (now deprecated).

For those who did not apply the manual fix from @tpokorra (thanks), I'm interested to know if the upgrade to v3.0.6 works fine.

**Comment by admorgan** [comment]
I have attempted to upgrade after the v3.0.6 and it still isn't working for Postgres for me.

An error occurred during the request. Unable to proceed.
Database error when running migration 030000Date20240911230019 for app cospend An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR: column "project_id" of relation "oc_cospend_bills" contains null values

**Comment by doomlaur** [comment]
I had the same issue with exactly the same error message like the others when using version 3.0.5.

With 3.0.6 I have the following error:
> Database error when running migration 030000Date20240921142937 for app cospend An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR: column "project_id" of relation "oc_cospend_paymentmodes" contains null values

This is with a PostgreSQL 16.3 database, Nextcloud 30.0.4 and PHP 8.3.15.

**Comment by JustACasual** [comment]
>  `oc_cospend_projects.user_id` column can now contain null. I forgot that there could be existing "anonymous" projects (now deprecated).




Isn't the problem more that the column is named "userid" and not "user_id"

**Comment by JustACasual** [comment]
getting a new error now:
> cospend new version available: 3.0.6
Error: Database error when running migration 030000Date20240911230019 for app cospend
An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "project_id" of relation "oc_cospend_bills" contains null values

**Comment by julien-nc** [comment]
v3.0.7 should fix the migration. I tested it with Postgres, from Cospend v2.0.0 to v3.0.7.

The issue was that creating a column that has NotNull set to true (a column that can't be null) does not work in Postgres when there is existing rows because it does not know what to put in the created column for the existing rows. This works fine in Sqlite and Mysql/Mariadb.

Anyway, the solution suggested by @tpokorra was implemented in the migrations:
* First create the column with NotNull to false
* Transfer the data from the old column
* Finally set NotNull to true again

**Comment by doomlaur** [comment]
@julien-nc I can confirm that it works again now. Thank you! :smile:

**Comment by julien-nc** [comment]
@doomlaur Thanks for the feedback.

**Comment by admorgan** [comment]
I also can confirm that 3.0.7 is working on my system.
