### ISSUE TITLE
Internal server error after upgrade 2.0.0 -> 3.0.7

### ISSUE THREAD

**Issue by zenlord** [julien-nc/cospend-nc#323]
Hi,
Just ran the GUI updater and updated +-5 apps, including Cospend. No errors were shown during the upgrade process. Cospend now refuses to open the application; Nextcloud shows an 'internal error' message with a reference to the logs.
These are my logs ('Fout' = 'error'):

```
Niveau | Application | Bericht | Tijd | Log entry actions
-- | -- | -- | -- | --
Fout | cospend | QueryNotFoundExceptionCould not resolve OCA\Cospend\Search\CospendSearchProvider! Class "OCA\Cospend\Search\CospendSearchProvider" does not existCould not load search provider dynamically: Could not resolve OCA\Cospend\Search\CospendSearchProvider! Class "OCA\Cospend\Search\CospendSearchProvider" does not exist | 26 dec 2024, 15:59:07 |  
Fout | no app in context | QueryExceptionCould not resolve OCA\Cospend\Service\ProjectService! Class "OCA\Cospend\Service\ProjectService" does not exist | 26 dec 2024, 15:59:06 |  
Fout | cospend | QueryNotFoundExceptionCould not resolve OCA\Cospend\Search\CospendSearchProvider! Class "OCA\Cospend\Search\CospendSearchProvider" does not existCould not load search provider dynamically: Could not resolve OCA\Cospend\Search\CospendSearchProvider! Class "OCA\Cospend\Search\CospendSearchProvider" does not exist | 26 dec 2024, 15:59:05 |  
Fout | cospend | QueryNotFoundExceptionCould not resolve OCA\Cospend\Search\CospendSearchProvider! Class "OCA\Cospend\Search\CospendSearchProvider" does not existCould not load search provider dynamically: Could not resolve OCA\Cospend\Search\CospendSearchProvider! Class "OCA\Cospend\Search\CospendSearchProvider" does not exist | 26 dec 2024, 15:59:00 |  
Fout | no app in context | QueryExceptionCould not resolve OCA\Cospend\Service\ProjectService! Class "OCA\Cospend\Service\ProjectService" does not exist | 26 dec 2024, 15:55:36 |  
Fout | cospend | QueryNotFoundExceptionCould not resolve OCA\Cospend\Search\CospendSearchProvider! Class "OCA\Cospend\Search\CospendSearchProvider" does not existCould not load search provider dynamically: Could not resolve OCA\Cospend\Search\CospendSearchProvider! Class "OCA\Cospend\Search\CospendSearchProvider" does not exist | 26 dec 2024, 15:55:36 |  
Fout | no app in context | RuntimeExceptionNo provider found for id account | 26 dec 2024, 15:55:27
```

Debian 11
PHP 8.2.26
Apache
Postgres 13.18
Nextcloud 30.2

**Comment by qgjdev** [comment]
Similar issue here.
Error message on my side is:
```
Exception: Database error when running migration 030007Date20241225163007 for app cospend
An exception occurred while executing a query: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'user_id' at row 1
Update failed
```

**Comment by julien-nc** [comment]
@zenlord This looks like a Php opcache issue on your side. You can try to reload the php-fpm service if you are using it or restart your containers if you are running NC with docker.

The `OCA\Cospend\Search\CospendSearchProvider` class does not exist anymore and is not referenced anywhere. So it seems old cached versions of some Php files are used on your side.

@qgjdev This is more similar to https://github.com/julien-nc/cospend-nc/issues/320
This might have been solved in v3.0.8 which is out.

**Comment by zenlord** [comment]
Apologies, @julien-nc you are right. Restarting php-fpm has resolved my issue.
Thank you for your work!

**Comment by qgjdev** [comment]
Well great, now all my projects are gone after upgrading to 3.0.8.

**Comment by julien-nc** [comment]
@qgjdev Check the values in the `userid` or `user_id` column of `oc_cospend_projects`.

Also, did the upgrade to v3.0.8 run fine or fail?

**Comment by olpabro** [comment]
I can confirm the same observation that @qgjdev had.
1. Tried to upgrade 2.0.0 > 3.0.7 resulted in an error message, NC not available.
2. Tried to manually downgrade to 2.0.0 made NC available again, but accessing cospend resulted in an internal server error.
3. Upgrade to 3.0.8 went fine, but no projects are visible. Downgrading to earlier versions (tried 3.0.4, 3.0.7, 2.0.0) worked and automatic upgrade to 3.0.8 went w/o errors, but data keeps being invisible.
Column `user_id` of `oc_cospend_projects` has value NULL for all my projects.

NC 30.0.4 MariaDB 10.11 Debian 12 32 bit / Linux 6.6 64 bit PHP 8.2

**Comment by qgjdev** [comment]
> @qgjdev Check the values in the `userid` or `user_id` column of `oc_cospend_projects`.
> 
> Also, did the upgrade to v3.0.8 run fine or fail?

user_id entries are all NULL. Since I didn't get any error message I suspect the upgrade to be run fine.

**Comment by qgjdev** [comment]
> @olpabro @qgjdev No idea how and why you ended up with NULL in `oc_cospend_projects.user_id`. The only recovery from there is to set the user_id values manually in the database. The projects will show up in the UI after that.

So the user_id will be the owner's user id?

**Comment by julien-nc** [comment]
Yes, this column contains the user ID of the project owner (the user who created the project).

**Comment by olpabro** [comment]
This worked for me. Thank you @julien-nc

**Comment by qgjdev** [comment]
Worked for me as well. Thanks!
