### ISSUE TITLE
Column not found: 1054 Unknown column 'date' in 'field list'

### ISSUE THREAD

**Issue by Markoise** [julien-nc/cospend-nc#324]
The following error appears when installing Cospend on NC 30.0.4

```
Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.
Database error when running migration 000304Date20200313092247 for app cospend An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'date' in 'field list'
```

Cospend was previously installed to try it out, but was removed again.

Now I really wanted to use it, but I can no longer get it installed.

**Comment by julien-nc** [comment]
That's weird. Have you made any manual change to your database?

Anyway, to install Cospend from scratch again you can:

* disable/remove the app
* delete the `oc_cospend_*` tables
* delete the rows in `oc_migrations` where app=cospend
* install the app again

It should run all the database migration steps again.

**Comment by Markoise** [comment]
This is how I tried it:
- occ app:remove cospend
- DROP TABLE IF EXISTS oc_cospend_projects, oc_cospend_members, oc_cospend_shares, oc_cospend_transactions;
- DELETE FROM oc_migrations WHERE app = "cospend";
- SELECT * FROM oc_migrations WHERE app = "cospend";
- occ app:install cospend

This is what happens after the next installation attempt:

```
Error: Database error when running migration 000304Date20200313092247 for app cospend
An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'date' in 'field list'
```

Do you have any other ideas?

**Comment by julien-nc** [comment]
You forgot to drop the `oc_cospend_bills` table so the migration step didn't create the table. You can just repeat all you've done with a few adjustments to the DROP query:
* add `oc_cospend_bills`
* add `oc_cospend_bill_owers`
* remove `oc_cospend_transactions` (it has never existed)
* add`oc_cospend_paymentmodes`
* add `oc_cospend_categories`
* add `oc_cospend_currencies`
* add `oc_cospend_invitations` (it's a recent one but just in case)

**Comment by Markoise** [comment]
Ah. Thanks alot. It works now. :-)
