### ISSUE TITLE
Project Settlement for individual - Failed to create bill

### ISSUE THREAD

**Issue by redpixy** [julien-nc/cospend-nc#94]
Hi, I'm trying create a bill for a individual amount settlement. But I getting the error - Failed to create bill

**Comment by cestmoimeme** [comment]
Bonjour Julien
J'écris en français : mon anglais est bof-bof ...  
Avez vous une date pour la prochaine version ? J'ai téléchargé et installé le code ayant vu que ce souci été réglé mais (sans doute mauvaise manip) cela n'a pas fonctionné.

Merci d'avance et surtout merci pour cette appli géniale !

**Comment by eneiluj** [comment]
Do you mind if I answer in english?

v1.4.2 is out! Could you confirm it works fine?

**Comment by cestmoimeme** [comment]
No problem even if I make mistakes in englsih

I just downloaded the last one (1.4.2-5) and tested it : yes it works fine !!! 
Thanks a lot for the job 🥇 👍
